name: cEssentials
version: '1.0'
main: me.cessentials.CEssentials
api-version: 1.19

commands:
  gmc:
    description: Gamemode Creative Command
    usage: /gmc
  gms:
    description: Gamemode Survival Command
    usage: /gms
  gma:
    description: Gamemode Adventure Command
    usage: /gma
  gmsp:
    description: Gamemode Spectator Command
    usage: /gmsp
  fly:
    description: Fly command
    usage: /fly
    aliases:
      - flight
      - vola
